### ISSUE TITLE
undefined $emarsysApiEventID

### ISSUE THREAD

**Issue by yohanespradono** [emartech/3rd-party-integrations-magento-M2#11]
When emarsys transactional email is disabled, this file throws an error.

Emarsys/Emarsys/Model/SendEmail.php line 325-328

`        $emarsysEventCollection = $this->emarsyseventsFactory->create()->getCollection()
            ->addFieldToFilter('store_id', ['eq' => $storeId])
            ->addFieldToFilter('event_id', ['eq' => $emarsysApiEventID]);`

because $emarsysApiEventID is undefined. It is happening when placing an order.

**Comment by laurent35240** [comment]
Hi,

I created PR #29 for fixing this issue.
In the meantime you can use my fork by putting these lines in your composer.json file

```json
{
    "require": {
        "emarsys/emarsys": "dev-master"
    },
    "repositories": {
        "emartech-3rd-party-integrations-magento-m2": {
            "type": "git",
            "url": "https://github.com/laurent35240/3rd-party-integrations-magento-M2"
        }
    }
}
```

**Comment by eghanin** [comment]
Thank you Yohanes and Laurent. appreciate your support and contribution

**Comment by eghanin** [comment]
this has been merged
