### ISSUE TITLE
Initial sync of customers times out on large numbers.

### ISSUE THREAD

**Issue by eghanin** [emartech/3rd-party-integrations-magento-M2#2]
depending on the servers performance, if the volume of synced customers / subscriber is large, the operation times out and the sync fails

**Comment by kensium** [comment]
Follow the below instructions to run the Initial DBload from commandline:
1. Download the attached initialDbLoad.php.txt file and rename to initialDbLoad.php
2. Place this file at Magento root directory
3. Execute this script (php initialDbLoad.php)  on the Magento root directory

This may take some time to complete based on the number of records.

[initialDbLoad.php.txt](https://github.com/emartech/3rd-party-integrations-magento-M2/files/1466873/initialDbLoad.php.txt)

**Comment by eghanin** [comment]
fixed in our new versions. 
we improved the performance with all bulk data exports
