### ISSUE TITLE
Cannot enter /admin/ when module is enabled (Magento 2.2.3 w. DI not compiled)

### ISSUE THREAD

**Issue by lbajsarowicz** [emartech/3rd-party-integrations-magento-M2#33]
## Expected behaviour

*Emarsys* module should not cause any side effect whether *DI* is compiled or not.

## Current behaviour

When *DI is compiled* application works as expected.
When *DI is not compiled* we cannot access the Admin panel

## Screenshots

![zrzut ekranu z 2018-03-07 00-48-00](https://user-images.githubusercontent.com/1639941/37067609-e0553304-21aa-11e8-814b-d15c34d9471a.png)

## Debug

1. Disabled all modules one - by - one, removed `/generated/` dir each time, trying to log in to admin panel
2. _Disabling Emarsys helped_ - Enabled Emarsys again and disabled DI one - by - one.
3. _Disabling one of DI helped_ `<preference for="\Magento\Framework\Mail\Template\TransportBuilder" type="Emarsys\Emarsys\Model\Template\TransportBuilder"/>`

**Comment by eghanin** [comment]
Thanks, 
We will look into it!

**Comment by laurent35240** [comment]
Hi,

We created this PR #34 that fix the issue.
