### ISSUE TITLE
Missing Key_id

### ISSUE THREAD

**Issue by tonlam** [emartech/3rd-party-integrations-magento-M2#94]
Hi guys, I try to sync contact to Emarsys from Magento, but got this error.
Customer field has been mapped.

`PUT  contact/?create_if_not_exists=1 {
    "key_id": false,
    "0": "ccc@gmail.com#9#17",
    "3": "ccc@gmail.com"
}`

**Comment by eghanin** [comment]
Hi, 
You need to  
Go to Emarsys -> Mapping -> Customer
1. click update schema
2. re-save the customer mapping

try again.
If this doesnt work, let us know ...

**Comment by tonlam** [comment]
Hello @eghanin, 

Thanks for your reply. I tried that, but still get the same error.

**Comment by tonlam** [comment]
I can sync contacnt now. I go to Installation Checklist and create missing field.
